name: PHP Codeception Tests - master

on:
  workflow_dispatch:
  #push:
  #schedule:
  #  - cron: "0 0 * * 0"

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-master.yml@main
    with:
      module-id: breakingnews
